---
title: "Create TAB1X01 as RDF data cube"
author: "mja@statgroup.dk"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: united
  pdf_document:
    toc: true
    highlight: zenburn
  md_document:
    variant: markdown_github
---


# Setup

This script creates RDF data cubes from .csv files.

```{r}
library(rrdfancillary)
library(rrdfcdisc)
library(rrdfqb)
library(rrdfqbcrnd0)
```

All files are stored in the directory
```{r}
targetDir<- "../res-ttl"
(targetDir)
```

# Load CSV files

```{r, eval=TRUE}
tab1x01ObsDataCsvFn<- file.path("../res-csv", "TAB1X01.csv")
tab1x01ObsData <- read.csv(tab1x01ObsDataCsvFn,stringsAsFactors=FALSE)

tab1x01MetaDataCsvFn<- file.path("../res-csv", "TAB1X01-Components.csv")
tab1x01MetaData <- read.csv(tab1x01MetaDataCsvFn,stringsAsFactors=FALSE)
```

# Create cube

```{r, eval=TRUE}
tab1x01.cube.fn<- BuildCubeFromDataFrames(tab1x01MetaData, tab1x01ObsData )
cat("TAB1X01 cube stored as ", normalizePath(tab1x01.cube.fn), "\n")
```
# Copy cube to destination directory

```{r, eval=TRUE}
targetFile<- file.path(targetDir,"CDISC-pilot-TAB1X01.ttl")

if (file.copy( tab1x01.cube.fn, targetFile, overwrite=TRUE)) {
   cat("RDF data cube copied to ", normalizePath(targetFile), "\n")
 }

```




# Session information
```{r, echo=TRUE}
sessionInfo()
```

