--
title: "Create TAB1X03 as RDF data cube"
author: "mja@statgroup.dk"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: united
  pdf_document:
    toc: true
    highlight: zenburn
  md_document:
    variant: markdown_github
---

# Introduction
This script creates RDF data cubes from .csv files.

# Setup

All files are stored in the directory
```{r}
targetName<- "TAB1X03"
print(targetName)
targetDir<- "../res-ttl"
rqtargetDir<- "../sparql-rq"
print(targetDir)
targetFile<- file.path(targetDir, paste("CDISC-pilot-", targetName, ".ttl", sep=""))
print(targetFile)
targetObsrqFile<- file.path(targetDir, paste("CDISC-pilot-", targetName, "-observations", ".rq", sep=""))
print(targetObsrqFile)
target2DrqFile<- file.path(rqtargetDir, paste( tolower(targetName), ".rq", sep=""))
print(target2DrqFile)
```

```{r, child='include_ttl.Rmd'}
```

```{r}

rowdimensions<-c(
        "crnd-dimension:sitegr1",
        "crnd-dimension:siteid" 
    )

statdimensions<- c(
    "crnd-dimension:procedure",
    "crnd-dimension:factor"
    )

coldimensions<- c(
"crnd-dimension:trt01p",    
"crnd-dimension:ittfl",   
"crnd-dimension:efffl",   
"crnd-dimension:comp24fl"
    )


coldimval.rq<-
    paste( forsparqlprefix,
          "select distinct ", paste0( sub("crnd-dimension:", "?", coldimensions ), collapse=" ")," where {",
          "?s", " a ", "qb:Observation  ;",
          paste0( "    ", "qb:dataSet",  " ", "ds:", "dataset", "-", domainName, " ;", collapse="\n"),
          paste0( "    ", coldimensions, " ", sub("crnd-dimension:", "?", coldimensions ), ";", collapse="\n"),
          "}",
          "order by ", paste0( sub("crnd-dimension:", "?", coldimensions ), collapse=" ")
)
ll<- strsplit(coldimval.rq,split="\n")
cat(paste(seq(length(unlist(ll))),unlist(ll),collapse="\n"),"\n")

coldimval<- NULL
coldimval<- as.data.frame(sparql.rdf(checkCube, coldimval.rq ), stringsAsFactors=FALSE)
knitr::kable(coldimval)

colstack<- paste("zz",seq(nrow(coldimval)),sep="")

cc<-cbind(coldimensions,t(coldimval[1,]))
cat(paste( cc[,1],cc[,2], sep=" ", collapse="; \n")," ;\n")

```

```{r}
vv<-expand.grid(colstack)

colz1.rq<- NULL
colz1.rq<-
    paste( forsparqlprefix,
          "select * where {",
          paste0( ## for each of column values
              "?col", seq(length(colvalues)), "z1URI", " a qb:Observation  ;",
              paste0( "    ", "qb:dataSet",  " ", "ds:", "dataset", "-", domainName, " ;", collapse="\n"),
              paste0( "    ", rowdimensions, " ", sub("crnd-dimension:", "?", rowdimensions ), ";", collapse="\n"),
              paste0( "    ", statdimensions, " ", sub("crnd-dimension:", "?", statdimensions), "z1", ";", collapse="\n"),
              " ",
              "    ", coldimension, " ", colvalues, " ;",    
              " ",                     
              "    crnd-measure:measure ",  "?col", seq(length(colvalues)), "z1",
              ".", " ",
              "optional{",
              "?col", seq(length(colvalues)), "z2URI", " a qb:Observation  ;",
              paste0( "    ", "qb:dataSet",  " ", "ds:", "dataset", "-", domainName, " ;", collapse="\n"),
              paste0( "    ", rowdimensions, " ", sub("crnd-dimension:", "?", rowdimensions ), ";", collapse="\n"),
              "      crnd-dimension:procedure code:procedure-percent; \n",
              "    crnd-dimension:factor code:factor-proportion;  \n",
              "    crnd-attribute:denominator ",  "?col", seq(length(colvalues)), "z2denominator; \n", 
              "    ", coldimension, " ", colvalues, " ;",    
              ## "    crnd-dimension:procedure ?procedurez2 ; \n",
              ## "    crnd-dimension:factor ?factorz2 ;  \n",
              " ",                     
              "    crnd-measure:measure ",  "?col", seq(length(colvalues)), "z2", " . \n",
              "?col", seq(length(colvalues)), "z1URI", " ", "crnd-dimension:procedure", " ", "code:procedure-count", " .",   
              "}", " .",
              collapse="\n"),
          "optional {",                     
          paste0("",
                 sub("crnd-dimension:", "?", rowdimensions), " ", "skos:prefLabel", " ", sub("crnd-dimension:", "?", rowdimensions), "value", ".", collapse="\n"),                     
          paste0(  rowdimensions , " ",
                 "rdfs:label", " ", sub("crnd-dimension:", "?", rowdimensions), "label" ,
                 " . ", 
                 collapse="\n"),
          "}",
          "
{ select  ?procedurez1 where {
   code:procedure skos:hasTopConcept ?procedurez1 .
   filter ( ?procedurez1 != code:procedure-percent )
   } }
",
"}"
)
cat(colz1.rq,file=target2DrqFile)
ll<- strsplit(colz1.rq,split="\n")
cat(paste(seq(length(unlist(ll))),unlist(ll),collapse="\n"),"\n")

colz1obs<- NULL
colz1obs<- as.data.frame(sparql.rdf(checkCube, colz1.rq ), stringsAsFactors=FALSE)
knitr::kable(colz1obs)

```


