--
title: "Create TAB1X02 as RDF data cube"
author: "mja@statgroup.dk"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: united
  pdf_document:
    toc: true
    highlight: zenburn
  md_document:
    variant: markdown_github
---

# Introduction
This script creates RDF data cubes from .csv files.

# Setup

All files are stored in the directory
```{r}
targetName<- "TAB2X01"
(targetName)
targetDir<- "../res-ttl"
(targetDir)
targetFile<- file.path(targetDir, paste("CDISC-pilot-", targetName, ".ttl", sep=""))
(targetFile)
targetObsrqFile<- file.path(targetDir, paste("CDISC-pilot-", targetName, "-observations", ".rq", sep=""))
(targetObsrqFile)
```

```{r, child='include_ttl.Rmd'}
```

```{r}

z12prop<- matrix(c(
"code:procedure-min", "code:none",
"code:procedure-max", "code:none",
"code:procedure-median", "code:none",
"code:procedure-mean", "code:none",
"code:procedure-stddev", "code:none",
"code:procedure-n ", "code:procedure-percent",
"code:procedure-count", "code:none"
    ), ncol=2,byrow=TRUE)
str(z12prop)
z12prop

rowdimensions<-c(
"crnd-dimension:agegr1"   ,
"crnd-dimension:race"     ,
"crnd-dimension:sex"      ,
"crnd-dimension:durdsgr1" ,
"crnd-dimension:bmiblgr1" ,
"crnd-dimension:ittfl"    ,
"crnd-dimension:procedure",
"crnd-dimension:factor"
    )

coldimension<- c("crnd-dimension:trt01p"   )
colvalues<- c( "code:trt01p-Placebo",
"code:trt01p-Xanomeline_High_Dose",
"code:trt01p-Xanomeline_Low_Dose",
"code:trt01p-_ALL_")               
              
contvarstat<-
c("factor-age",
"factor-mmsetot", 
"factor-durdis",  
"factor-educlvl", 
"factor-heightbl",
"factor-weightbl",
"factor-bmibl"
)
    
contvarstatprocedure<-
c("code:procedure-percent",
"code:procedure-count"
)
    
catvardimensions1<-
    c(
"crnd-dimension:agegr1"   ,
"crnd-dimension:race"     ,
"crnd-dimension:sex"      ,
"crnd-dimension:durdsgr1" ,
"crnd-dimension:bmiblgr1" ,
"crnd-dimension:ittfl"    
        )

cube.rowdimsStat.rq<-
    paste( forsparqlprefix,
          paste0( "select distinct ", paste0(sub("crnd-dimension:", "?", rowdimensions ), collapse=" "), " where {", collapse="\n"),
          "{select * where {",
          "?s a qb:Observation  ;", 
          paste0( "    ", "qb:dataSet",  " ", "ds:", "dataset", "-", domainName, " ;", collapse="\n"),
          paste0( "    ", rowdimensions, " ", sub("crnd-dimension:", "?", rowdimensions ), ";", collapse="\n"),
          "    crnd-dimension:procedure ?procedure ; ",
          "    crnd-dimension:factor ?factor .      ",
          "     values (?factor) {",
          paste0( "     ", "(", "code:", contvarstat, ")", collapse="\n"),
          "}}",
          "} ",
          "union",
          "{select * where {",
          "?s a qb:Observation  ;", 
          paste0( "    ", "qb:dataSet",  " ", "ds:", "dataset", "-", domainName, " ;", collapse="\n"),
          paste0( "    ", catvardimensions1, " ", sub("crnd-dimension:", "?", catvardimensions1 ), ";", collapse="\n"),
          "    crnd-dimension:procedure ?procedure ; ",
          "    crnd-dimension:factor ?factor .      ",
          "     values (?procedure) {",
          paste0( "     ", "(", contvarstatprocedure, ")", collapse="\n"),
          "}}",
          "}",          
          "} ",
          "\n",
          sep="\n", collapse="\n"
          )
cat(cube.rowdimsStat.rq)

observationsRowDims<- as.data.frame(sparql.rdf(checkCube, cube.rowdimsStat.rq ), stringsAsFactors=FALSE)
knitr::kable(observationsRowDims)


cube.rowdimsStat.rq<-
    paste( forsparqlprefix,
          paste0( "select distinct ", paste0(sub("crnd-dimension:", "?", rowdimensions ), collapse=" "), " where {", collapse="\n"),
          "{select * where {",
          "?s a qb:Observation  ;", 
          paste0( "    ", "qb:dataSet",  " ", "ds:", "dataset", "-", domainName, " ;", collapse="\n"),
          paste0( "    ", rowdimensions, " ", sub("crnd-dimension:", "?", rowdimensions ), ";", collapse="\n"),
          "    crnd-dimension:procedure ?procedure ; ",
          "    crnd-dimension:factor ?factor .      ",
          "     values (?factor) {",
          paste0( "     ", "(", "code:", contvarstat, ")", collapse="\n"),
          "}}",
          "} ",
          "union",
          "{select * where {",
          "?s a qb:Observation  ;", 
          paste0( "    ", "qb:dataSet",  " ", "ds:", "dataset", "-", domainName, " ;", collapse="\n"),
          paste0( "    ", catvardimensions1, " ", sub("crnd-dimension:", "?", catvardimensions1 ), ";", collapse="\n"),
          "    crnd-dimension:procedure ?procedure ; ",
          "    crnd-dimension:factor ?factor .      ",
          "     values (?procedure) {",
          paste0( "     ", "(", contvarstatprocedure, ")", collapse="\n"),
          "}}",
          "}",          
          "} ",
          "\n",
          sep="\n", collapse="\n"
          )
cat(cube.rowdimsStat.rq)

observationsRowDims<- as.data.frame(sparql.rdf(checkCube, cube.rowdimsStat.rq ), stringsAsFactors=FALSE)
knitr::kable(observationsRowDims)

## ================================================================

cube.rowdimscol1obs.rq<-
    paste( forsparqlprefix,
          "select * where {",


          "{",
          paste0( "select distinct ", paste0(sub("crnd-dimension:", "?", rowdimensions ), collapse=" "), " where {", collapse="\n"),
          "{select * where {",
          "?s a qb:Observation  ;", 
          paste0( "    ", "qb:dataSet",  " ", "ds:", "dataset", "-", domainName, " ;", collapse="\n"),
          paste0( "    ", rowdimensions, " ", sub("crnd-dimension:", "?", rowdimensions ), ";", collapse="\n"),
          "    crnd-dimension:procedure ?procedure ; ",
          "    crnd-dimension:factor ?factor .      ",
          "     values (?factor) {",
          paste0( "     ", "(", "code:", contvarstat, ")", collapse="\n"),
          "}}",
          "} ",
          "union",
          "{select * where {",
          "?s a qb:Observation  ;", 
          paste0( "    ", "qb:dataSet",  " ", "ds:", "dataset", "-", domainName, " ;", collapse="\n"),
          paste0( "    ", catvardimensions1, " ", sub("crnd-dimension:", "?", catvardimensions1 ), ";", collapse="\n"),
          "    crnd-dimension:procedure ?procedure ; ",
          "    crnd-dimension:factor ?factor .      ",
          "     values (?procedure) {",
          paste0( "     ", "(", contvarstatprocedure, ")", collapse="\n"),
          "}}",
          "}",          
          "} ",
          "} ",

          "values (?z1prop ?z2prop) {",
paste( "(", z12prop[,1], z12prop[,2], ")", sep=" ", collapse="\n"),
          "} ",

          paste0(
          "optional{ ?s", seq(length(colvalues)), "z1", " a qb:Observation  ;", 
          paste0( "    ", "qb:dataSet",  " ", "ds:", "dataset", "-", domainName, " ;", collapse="\n"),
          paste0( "    ", rowdimensions, " ", sub("crnd-dimension:", "?", rowdimensions ), ";", collapse="\n"),
          "    crnd-dimension:factor ?factor ;      ",
          "    ", coldimension, " ", colvalues, " ;",
          "    crnd-measure:measure ?col", seq(length(colvalues)), "z1", " ;  ",
              "  crnd-dimension:procedure ?z1prop . }", collapse="\n"
              ),

          paste0(
          "optional{ ?s", seq(length(colvalues)), "z2", " a qb:Observation  ;", 
          paste0( "    ", "qb:dataSet",  " ", "ds:", "dataset", "-", domainName, " ;", collapse="\n"),
          paste0( "    ", rowdimensions, " ", sub("crnd-dimension:", "?", rowdimensions ), ";", collapse="\n"),
          "    crnd-dimension:factor ?factor ;      ",
          "    ", coldimension, " ", colvalues, " ;",
          "    crnd-measure:measure ?col", seq(length(colvalues)), "z2", " ;  ",
              "  crnd-dimension:procedure ?z2prop . }", collapse="\n"
              ),
                    
          "} ",
          "\n",
          sep="\n", collapse="\n"
          )
cat(cube.rowdimscol1obs.rq)

observationscol1obs<- as.data.frame(sparql.rdf(checkCube, cube.rowdimscol1obs.rq ), stringsAsFactors=FALSE)
knitr::kable(observationscol1obs)



```


